temp_folder: ~/tmp
node_version: 20

app_user: your_app_user
app_password: your_app_password

postgresql_databases:
  - name: your_db_name
    owner: your_app_user
postgresql_users:
  - name: your_app_user
    password: your_db_password
